### ISSUE TITLE
[TODO] Interface of expander has to be checked again after prototype of executor

### ISSUE THREAD

**Issue by itislu** [LeaYeh/minishell#75]
- [ ] When should the expander create a list with empty content and when should the list just be NULL?
    I think atm the following line is incorrect:
  ```c
	if (!*dup)
		return (free_and_reset(dup, NULL), true);
  ```
  It should still create a list with content being NULL.

- [ ] Possibly `clean_and_exit_shell()` can also be used in expander for general errors.

- [ ] Once the interface is set up, document with real examples what the expander returns and what it will mean.
